//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWSDeploymentAssistant.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string DefaultLoggerName {
            get {
                return ((string)(this["DefaultLoggerName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>obj\</string>
  <string>Web.Debug.config</string>
  <string>Web.Release.config</string>
  <string>packages.config</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PublishFileTypesExcludePattern {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PublishFileTypesExcludePattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.dll</string>
  <string>.css</string>
  <string>.js</string>
  <string>.xml</string>
  <string>.xsl</string>
  <string>.xslt</string>
  <string>.xsd</string>
  <string>.htm</string>
  <string>.html</string>
  <string>.xhtml</string>
  <string>.cshtml</string>
  <string>.aspx</string>
  <string>.ascx</string>
  <string>.asax</string>
  <string>.asmx</string>
  <string>.axd</string>
  <string>.config</string>
  <string>.ico</string>
  <string>.jpg</string>
  <string>.gif</string>
  <string>.png</string>
  <string>.eot</string>
  <string>.svg</string>
  <string>.ttf</string>
  <string>.woff</string>
  <string>.woff2</string>
  <string>.otf</string>
  <string>.exe</string>
  <string>.json</string>
  <string>.swf</string>
  <string>.swz</string>
  <string>.ashx</string>
  <string>.asp</string>
  <string>.rdf</string>
  <string>.flv</string>
  <string>.svc</string>
  <string>.mime</string>
  <string>.rss</string>
  <string>.atom</string>
  <string>.yml</string>
  <string>.ps1</string>
  <string>.zip</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PublishFileTypesIncludePattern {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PublishFileTypesIncludePattern"]));
            }
        }
    }
}
